spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  #DB ??
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create   # 처음 실행시는 create ddl 명령어로 테이블 생성하고,(첫 spring 기동) 두번째는 update로 변경, 운영 배포시 none으로 변경 요청
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher